import { defineStore } from 'pinia'

export const useMainStore = defineStore('main', {
  state: () => ({
    activities: [
      {
        id: 1,
        name: 'Fitness & Musculation',
        description: 'Renforcement musculaire et exercices fonctionnels en plein air. Utilisez votre poids corporel et des équipements portables.',
        schedule: 'Samedi - 8h00-9h30',
        location: 'Parc de la Révolution',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        color: 'cacao',
        benefits: ['Renforcement musculaire', 'Amélioration cardio', 'Perte de poids', 'Tonification'],
        instructor: 'Coach Michel',
        level: 'Tous niveaux',
        equipment: 'Élastiques, haltères portables, tapis de sol',
        address: 'Parc de la Révolution, Brazzaville',
        capacity: 30,
        price: '1500 FCFA/mois',
        duration: '1h30',
        difficulty: 'Tous niveaux',
        maxAge: 'Aucune limite',
        minAge: 16,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Tenue de sport confortable',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Gratuit',
        showers: 'Non disponibles',
        wifi: 'Gratuit',
        lockers: 'Non disponibles',
        airConditioning: 'Non (plein air)',
        music: 'Playlist motivante',
        firstClass: 'Samedi 8h00',
        lastClass: 'Samedi 9h30',
        totalClasses: '4 par mois',
        waitingList: 'Oui',
        cancellationPolicy: '24h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -20%', 'Groupes: -15%'],
        activityStatus: 'Active',
        currentParticipants: 18
      },
      {
        id: 2,
        name: 'Club de Slam & Lecture',
        description: 'Découvrez la poésie orale, partagez vos lectures et développez votre expression. Une activité culturelle pour enrichir l\'esprit et la créativité.',
        schedule: 'Samedi - 16h00-17h30',
        location: 'Place de la Paix',
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop',
        color: 'raspberry',
        benefits: ['Expression orale', 'Enrichissement culturel', 'Stimulation créative', 'Partage en groupe'],
        instructor: 'Coach Sarah',
        level: 'Tous niveaux',
        equipment: 'Livres, micro, système audio portable',
        address: 'Place de la Paix, Centre-ville, Brazzaville',
        capacity: 20,
        price: '5 000 FCFA/mois',
        duration: '1h30',
        difficulty: 'Tous niveaux',
        maxAge: 'Aucune limite',
        minAge: 12,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Carnet de notes, stylo',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Gratuit',
        showers: 'Non disponibles',
        wifi: 'Gratuit',
        lockers: 'Non disponibles',
        airConditioning: 'Non (plein air)',
        music: 'Ambiance calme et inspirante',
        firstClass: 'Samedi 16h00',
        lastClass: 'Samedi 17h30',
        totalClasses: '4 par mois',
        waitingList: 'Oui',
        cancellationPolicy: '24h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -30%', 'Groupes: -25%'],
        activityStatus: 'Active',
        currentParticipants: 12
      },
      {
        id: 3,
        name: 'Cardio Plein Air',
        description: 'Course à pied et exercices en extérieur dans la nature. Profitez du grand air pour vos séances cardio.',
        schedule: 'Samedi - 7h00-8h30',
        location: 'Parc de la Révolution',
        image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop',
        color: 'sunny',
        benefits: ['Endurance cardio', 'Vitesse', 'Plein air', 'Nature'],
        instructor: 'Coach Jean',
        level: 'Tous niveaux',
        equipment: 'Baskets de course',
        address: 'Parc de la Révolution, Brazzaville',
        capacity: 40,
        price: '1000 FCFA/mois',
        duration: '1h30',
        difficulty: 'Tous niveaux',
        maxAge: 'Aucune limite',
        minAge: 14,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Baskets de course et bouteille d\'eau',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Gratuit',
        showers: 'Non disponibles',
        wifi: 'Non disponible',
        lockers: 'Non disponibles',
        airConditioning: 'Non (plein air)',
        music: 'Nature et motivation',
        firstClass: 'Samedi 7h00',
        lastClass: 'Samedi 8h30',
        totalClasses: '4 par mois',
        waitingList: 'Non',
        cancellationPolicy: '2h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -30%', 'Groupes: -25%'],
        activityStatus: 'Active',
        currentParticipants: 28
      }
    ],
    events: [
      {
        id: 1,
        title: 'Marathon de Brazzaville',
        date: '2025-03-15',
        time: '7h00',
        location: 'Centre-ville de Brazzaville',
        description: 'Course de 10km ouverte à tous les niveaux. Parcours urbain avec vue sur le fleuve Congo.',
        image: '/images/marathon.jpg',
        registrationRequired: true,
        maxParticipants: 500,
        price: 'Gratuit',
        organizer: 'FlexBeat en partenariat avec la Mairie',
        category: 'Course à pied',
        duration: '3 heures',
        ageMin: 16,
        registrationDeadline: '2025-03-10',
        prizes: ['Médaille pour tous', 'Trophées pour les 3 premiers'],
        sponsors: ['Mairie de Brazzaville', 'Orange Congo', 'Total Energies'],
        route: 'Départ: Place de la République - Arrivée: Place de la Paix',
        weather: 'Saison sèche, température agréable',
        facilities: ['Points de ravitaillement', 'Médecins', 'Toilettes'],
        contact: 'marathon@flexbeat.cg',
        phone: '+242 06 123 45 67',
        website: 'www.marathon-brazzaville.cg',
        socialMedia: '@marathon_brazzaville',
        registrationLink: 'https://forms.gle/marathon2025',
        maxRegistrationDate: '2025-03-10',
        startLocation: 'Place de la République',
        finishLocation: 'Place de la Paix',
        elevation: '120m',
        distance: '10km',
        terrain: 'Urbain',
        waterStations: 5,
        medicalStations: 3,
        timingChip: 'Oui',
        eventType: 'Compétition',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 2,
        title: 'Festival du Sport',
        date: '2025-02-20',
        time: '14h00',
        location: 'Stade Alphonse Massamba-Débat',
        description: 'Démonstrations et initiations sportives pour toute la famille. Stands, animations et compétitions.',
        image: '/images/festival.jpg',
        registrationRequired: false,
        maxParticipants: 1000,
        price: 'Gratuit',
        organizer: 'FlexBeat',
        category: 'Festival',
        duration: '6 heures',
        ageMin: 'Tous âges',
        registrationDeadline: 'N/A',
        prizes: ['Animations gratuites', 'Initiation aux sports'],
        sponsors: ['Ministère des Sports', 'Fédération Congolaise'],
        route: 'Stade Alphonse Massamba-Débat - Stands et animations',
        weather: 'Saison sèche, ensoleillé',
        facilities: ['Stands de restauration', 'Animations pour enfants', 'Parking gratuit'],
        contact: 'festival@flexbeat.cg',
        phone: '+242 06 123 45 68',
        website: 'www.festival-sport-congo.cg',
        socialMedia: '@festival_sport_congo',
        registrationLink: 'N/A',
        maxRegistrationDate: 'N/A',
        startLocation: 'Stade Alphonse Massamba-Débat',
        finishLocation: 'Stade Alphonse Massamba-Débat',
        elevation: '320m',
        distance: 'N/A',
        terrain: 'Stade',
        waterStations: 'N/A',
        medicalStations: 2,
        timingChip: 'Non',
        eventType: 'Festival',
        registrationStatus: 'Non requis',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 3,
        title: 'Stage de Slam & Poésie',
        date: '2025-01-25',
        time: '10h00',
        location: 'Place de la Paix',
        description: 'Stage intensif de slam et poésie orale en plein air. Tous niveaux acceptés.',
        image: '/images/slam-stage.jpg',
        registrationRequired: true,
        maxParticipants: 30,
        price: '25 000 FCFA',
        organizer: 'Coach Sarah',
        category: 'Stage',
        duration: '4 heures',
        ageMin: 12,
        registrationDeadline: '2025-01-20',
        prizes: ['Certificat de participation', 'Spectacle de fin de stage'],
        sponsors: ['Place de la Paix', 'Association des Poètes'],
        route: 'Place de la Paix - Spectacle final',
        weather: 'Saison sèche, plein air',
        facilities: ['Espace ombragé', 'Matériel fourni', 'Eau disponible'],
        contact: 'slam@flexbeat.cg',
        phone: '+242 06 123 45 69',
        website: 'www.stage-slam-congo.cg',
        socialMedia: '@stage_slam_congo',
        registrationLink: 'https://forms.gle/slam2025',
        maxRegistrationDate: '2025-01-20',
        startLocation: 'Place de la Paix',
        finishLocation: 'Place de la Paix',
        elevation: '280m',
        distance: 'N/A',
        terrain: 'Plein air',
        waterStations: 'N/A',
        medicalStations: 1,
        timingChip: 'Non',
        eventType: 'Stage',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 4,
        title: 'Challenge Fitness Plein Air',
        date: '2025-04-10',
        time: '16h00',
        location: 'Parc de la Révolution',
        description: 'Compétition de fitness en plein air par équipes. Épreuves de force, endurance et coordination.',
        image: '/images/fitness-challenge.jpg',
        registrationRequired: true,
        maxParticipants: 100,
        price: '15 000 FCFA',
        organizer: 'Coach Michel',
        category: 'Compétition',
        duration: '2 heures',
        ageMin: 18,
        registrationDeadline: '2025-04-05',
        prizes: ['Trophées pour les 3 premières équipes', 'Médaille pour tous les participants'],
        sponsors: ['Parc de la Révolution', 'Fédération de Fitness'],
        route: 'Parc de la Révolution - Épreuves par équipes',
        weather: 'Saison des pluies, plein air',
        facilities: ['Espace ombragé', 'Matériel de compétition', 'Eau disponible'],
        contact: 'fitness@flexbeat.cg',
        phone: '+242 06 123 45 70',
        website: 'www.challenge-fitness-congo.cg',
        socialMedia: '@challenge_fitness_congo',
        registrationLink: 'https://forms.gle/fitness2025',
        maxRegistrationDate: '2025-04-05',
        startLocation: 'Parc de la Révolution',
        finishLocation: 'Parc de la Révolution',
        elevation: '120m',
        distance: 'N/A',
        terrain: 'Plein air',
        waterStations: 'N/A',
        medicalStations: 2,
        timingChip: 'Oui',
        eventType: 'Compétition',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      }
    ],
    testimonials: [
      {
        id: 1,
        name: 'Marie K.',
        role: 'Membre depuis 2 ans',
        content: 'FlexBeat m\'a permis de retrouver la forme et de rencontrer des personnes passionnées par le sport. L\'ambiance est incroyable !',
        avatar: '/images/avatar1.jpg',
        activity: 'Fitness',
        rating: 5,
        age: 28,
        profession: 'Infirmière',
        joinDate: '2022-01-15',
        favoriteActivity: 'Renforcement musculaire',
        goals: 'Perte de poids et tonification',
        achievements: 'Perdu 8kg, amélioré ma condition physique',
        frequency: '3 fois par semaine',
        motivation: 'Santé et bien-être',
        location: 'Brazzaville Centre',
        socialMedia: '@marie_fitness',
        beforeWeight: '68kg',
        afterWeight: '60kg',
        favoriteCoach: 'Coach Michel',
        favoriteTime: '18h00',
        favoriteDay: 'Mercredi',
        beforePhoto: '/images/before-marie.jpg',
        afterPhoto: '/images/after-marie.jpg',
        totalClasses: 156,
        favoriteEquipment: 'Haltères',
        personalBest: 'Squat 50kg',
        membershipType: 'Annuel',
        referralCount: 3,
        favoriteClass: 'Renforcement musculaire',
        improvement: 'Très satisfaite',
        testimonialDate: '2024-12-01',
        verified: true
      },
      {
        id: 2,
        name: 'Jean P.',
        role: 'Membre depuis 1 an',
        content: 'Les séances sont variées et adaptées à tous les niveaux. L\'ambiance est excellente et les coachs sont très professionnels !',
        avatar: '/images/avatar2.jpg',
        activity: 'Cardio',
        rating: 5,
        age: 35,
        profession: 'Ingénieur',
        joinDate: '2023-01-10',
        favoriteActivity: 'Course à pied',
        goals: 'Améliorer mon endurance cardio',
        achievements: 'Parcours 10km en 45 minutes',
        frequency: '2 fois par semaine',
        motivation: 'Performance sportive',
        location: 'Brazzaville Nord',
        socialMedia: '@jean_runner',
        beforeTime: '55 minutes',
        afterTime: '45 minutes',
        favoriteCoach: 'Coach Jean',
        favoriteTime: '7h00',
        favoriteDay: 'Samedi',
        beforePhoto: '/images/before-jean.jpg',
        afterPhoto: '/images/after-jean.jpg',
        totalClasses: 52,
        favoriteEquipment: 'Chronomètre',
        personalBest: '10km en 45 minutes',
        membershipType: 'Annuel',
        referralCount: 1,
        favoriteClass: 'Course à pied',
        improvement: 'Très satisfait',
        testimonialDate: '2024-11-28',
        verified: true
      },
      {
        id: 3,
        name: 'Sarah M.',
        role: 'Membre depuis 6 mois',
        content: 'J\'adore le Club de Slam & Lecture ! C\'est une excellente façon de développer ma créativité et de partager avec d\'autres passionnés.',
        avatar: '/images/avatar3.jpg',
        activity: 'Club de Slam & Lecture',
        rating: 5,
        age: 24,
        profession: 'Étudiante',
        joinDate: '2023-07-01',
        favoriteActivity: 'Poésie orale',
        goals: 'Développer l\'expression orale et la créativité',
        achievements: 'Participé au spectacle de fin d\'année',
        frequency: '1 fois par semaine',
        motivation: 'Culture et créativité',
        location: 'Brazzaville Sud',
        socialMedia: '@sarah_slam',
        beforeLevel: 'Débutant',
        afterLevel: 'Intermédiaire',
        favoriteCoach: 'Coach Sarah',
        favoriteTime: '16h00',
        favoriteDay: 'Samedi',
        beforePhoto: '/images/before-sarah.jpg',
        afterPhoto: '/images/after-sarah.jpg',
        totalClasses: 26,
        favoriteEquipment: 'Micro',
        personalBest: 'Spectacle de fin d\'année',
        membershipType: 'Mensuel',
        referralCount: 2,
        favoriteClass: 'Poésie orale',
        improvement: 'Très satisfaite',
        testimonialDate: '2024-11-25',
        verified: true
      },
      {
        id: 4,
        name: 'David L.',
        role: 'Membre depuis 3 ans',
        content: 'Le cardio plein air est parfait pour moi. C\'est motivant de faire du sport en groupe dans la nature de Brazzaville.',
        avatar: '/images/avatar4.jpg',
        activity: 'Cardio',
        rating: 5,
        age: 42,
        profession: 'Enseignant',
        joinDate: '2021-03-20',
        favoriteActivity: 'Exercices en plein air',
        goals: 'Maintenir une bonne condition physique',
        achievements: 'Membre fidèle, ambassadeur FlexBeat',
        frequency: '1 fois par semaine',
        motivation: 'Santé et nature',
        location: 'Brazzaville Est',
        socialMedia: '@david_outdoor',
        beforeCondition: 'Moyenne',
        afterCondition: 'Excellente',
        favoriteCoach: 'Coach Jean',
        favoriteTime: '7h00',
        favoriteDay: 'Samedi',
        beforePhoto: '/images/before-david.jpg',
        afterPhoto: '/images/after-david.jpg',
        totalClasses: 156,
        favoriteEquipment: 'Gilet réfléchissant',
        personalBest: 'Ambassadeur FlexBeat',
        membershipType: 'Annuel',
        referralCount: 5,
        favoriteClass: 'Exercices en plein air',
        improvement: 'Très satisfait',
        testimonialDate: '2024-11-20',
        verified: true
      }
    ],
    gallery: [
      {
        id: 1,
        title: 'Séance de Fitness en Plein Air',
        category: 'fitness',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Groupe de fitness en pleine séance de renforcement musculaire au Parc de la Révolution',
        date: '2024-12-01',
        photographer: 'Coach Michel',
        tags: ['fitness', 'groupe', 'musculation', 'plein air'],
        likes: 45,
        views: 120,
        location: 'Parc de la Révolution, Brazzaville',
        participants: 15,
        equipment: ['Élastiques', 'Haltères portables', 'Tapis de sol'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '28°C',
        hashtags: ['#FlexBeat', '#Fitness', '#Brazzaville', '#PleinAir'],
        camera: 'Canon EOS R6',
        settings: 'f/2.8, 1/200s, ISO 400',
        resolution: '4000x3000',
        fileSize: '8.5 MB',
        uploadDate: '2024-12-01',
        lastModified: '2024-12-01',
        featured: true,
        downloadCount: 12,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 1,
        isPublic: true
      },
      {
        id: 2,
        title: 'Club de Slam & Lecture',
        category: 'slam',
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
        description: 'Séance de slam et lecture en plein air à la Place de la Paix',
        date: '2024-11-28',
        photographer: 'Coach Sarah',
        tags: ['slam', 'lecture', 'poésie', 'culture', 'plein air'],
        likes: 38,
        views: 95,
        location: 'Place de la Paix, Centre-ville, Brazzaville',
        participants: 12,
        equipment: ['Livres', 'Micro portable', 'Système audio'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '30°C',
        hashtags: ['#FlexBeat', '#Slam', '#Lecture', '#Culture'],
        camera: 'Sony A7 III',
        settings: 'f/4.0, 1/160s, ISO 800',
        resolution: '4000x3000',
        fileSize: '7.2 MB',
        uploadDate: '2024-11-28',
        lastModified: '2024-11-28',
        featured: false,
        downloadCount: 8,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 2,
        isPublic: true
      },
      {
        id: 3,
        title: 'Cardio Plein Air au Parc',
        category: 'cardio',
        image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=300&fit=crop',
        description: 'Séance de cardio dans le parc de la Révolution avec vue sur la nature',
        date: '2024-11-25',
        photographer: 'Coach Jean',
        tags: ['cardio', 'plein air', 'parc', 'course'],
        likes: 52,
        views: 135,
        location: 'Parc de la Révolution',
        participants: 25,
        equipment: ['Cones de course', 'Chronomètres', 'Gilets réfléchissants'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '26°C',
        hashtags: ['#FlexBeat', '#Cardio', '#PleinAir', '#Nature'],
        camera: 'Nikon Z6',
        settings: 'f/5.6, 1/125s, ISO 200',
        resolution: '4000x3000',
        fileSize: '9.1 MB',
        uploadDate: '2024-11-25',
        lastModified: '2024-11-25',
        featured: true,
        downloadCount: 15,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 3,
        isPublic: true
      },
      {
        id: 4,
        title: 'Festival du Sport 2024',
        category: 'evenements',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Festival du sport avec stands et animations pour toute la famille',
        date: '2024-11-20',
        photographer: 'Équipe FlexBeat',
        tags: ['événement', 'festival', 'sport', 'famille'],
        likes: 67,
        views: 180,
        location: 'Stade Alphonse Massamba-Débat',
        participants: 300,
        equipment: ['Stands d\'exposition', 'Matériel sportif', 'Système de son'],
        duration: '6 heures',
        season: 'Saison sèche',
        temperature: '32°C',
        hashtags: ['#FlexBeat', '#FestivalSport', '#Congo', '#Famille'],
        camera: 'Canon EOS R5',
        settings: 'f/3.2, 1/100s, ISO 640',
        resolution: '4000x3000',
        fileSize: '10.3 MB',
        uploadDate: '2024-11-20',
        lastModified: '2024-11-20',
        featured: true,
        downloadCount: 22,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 4,
        isPublic: true
      },
      {
        id: 5,
        title: 'Équipe FlexBeat en Action',
        category: 'fitness',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Équipe de fitness FlexBeat lors d\'une séance d\'entraînement',
        date: '2024-11-18',
        photographer: 'Coach Michel',
        tags: ['fitness', 'équipe', 'groupe', 'entraînement'],
        likes: 41,
        views: 110,
        location: 'Parc de la Révolution',
        participants: 18,
        equipment: ['Haltères', 'Tapis de sol', 'Élastiques'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '29°C',
        hashtags: ['#FlexBeat', '#Fitness', '#Équipe', '#Motivation'],
        camera: 'Canon EOS R6',
        settings: 'f/4.0, 1/160s, ISO 400',
        resolution: '4000x3000',
        fileSize: '8.8 MB',
        uploadDate: '2024-11-18',
        lastModified: '2024-11-18',
        featured: false,
        downloadCount: 10,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 5,
        isPublic: true
      },
      {
        id: 6,
        title: 'Séance de Stretching Matinal',
        category: 'fitness',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Étirements et récupération en plein air au lever du soleil',
        date: '2024-11-15',
        photographer: 'Coach Sarah',
        tags: ['stretching', 'récupération', 'matin', 'plein air'],
        likes: 35,
        views: 88,
        location: 'Parc de la Révolution',
        participants: 12,
        equipment: ['Tapis de yoga', 'Blocs de yoga'],
        duration: '45 minutes',
        season: 'Saison sèche',
        temperature: '24°C',
        hashtags: ['#FlexBeat', '#Stretching', '#Récupération', '#Matin'],
        camera: 'Sony A7 III',
        settings: 'f/2.8, 1/125s, ISO 200',
        resolution: '4000x3000',
        fileSize: '7.5 MB',
        uploadDate: '2024-11-15',
        lastModified: '2024-11-15',
        featured: false,
        downloadCount: 6,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 6,
        isPublic: true
      },
      {
        id: 7,
        title: 'Marathon de Brazzaville - Départ',
        category: 'evenements',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Moment de départ du Marathon de Brazzaville avec tous les participants',
        date: '2024-11-10',
        photographer: 'Équipe FlexBeat',
        tags: ['marathon', 'course', 'événement', 'départ'],
        likes: 89,
        views: 250,
        location: 'Place de la République, Brazzaville',
        participants: 500,
        equipment: ['Dossards', 'Chronométrage', 'Médecins'],
        duration: '3 heures',
        season: 'Saison sèche',
        temperature: '27°C',
        hashtags: ['#FlexBeat', '#Marathon', '#Brazzaville', '#Course'],
        camera: 'Canon EOS R5',
        settings: 'f/5.6, 1/200s, ISO 100',
        resolution: '4000x3000',
        fileSize: '11.2 MB',
        uploadDate: '2024-11-10',
        lastModified: '2024-11-10',
        featured: true,
        downloadCount: 28,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 7,
        isPublic: true
      },
      {
        id: 8,
        title: 'Atelier de Slam & Poésie',
        category: 'slam',
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
        description: 'Atelier créatif de slam et poésie pour jeunes talents',
        date: '2024-11-08',
        photographer: 'Coach Sarah',
        tags: ['slam', 'poésie', 'atelier', 'créativité'],
        likes: 42,
        views: 95,
        location: 'Place de la Paix',
        participants: 8,
        equipment: ['Micro', 'Système audio', 'Livres de poésie'],
        duration: '2 heures',
        season: 'Saison sèche',
        temperature: '31°C',
        hashtags: ['#FlexBeat', '#Slam', '#Poésie', '#Créativité'],
        camera: 'Sony A7 III',
        settings: 'f/3.5, 1/100s, ISO 640',
        resolution: '4000x3000',
        fileSize: '8.1 MB',
        uploadDate: '2024-11-08',
        lastModified: '2024-11-08',
        featured: false,
        downloadCount: 7,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 8,
        isPublic: true
      },
      {
        id: 9,
        title: 'Entraînement Cardio Intensif',
        category: 'cardio',
        image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=300&fit=crop',
        description: 'Séance de cardio intensif avec exercices variés en plein air',
        date: '2024-11-05',
        photographer: 'Coach Jean',
        tags: ['cardio', 'intensif', 'exercices', 'plein air'],
        likes: 58,
        views: 142,
        location: 'Parc de la Révolution',
        participants: 22,
        equipment: ['Cones', 'Chronomètres', 'Gilets réfléchissants'],
        duration: '1h15',
        season: 'Saison sèche',
        temperature: '28°C',
        hashtags: ['#FlexBeat', '#Cardio', '#Intensif', '#Motivation'],
        camera: 'Nikon Z6',
        settings: 'f/4.0, 1/160s, ISO 400',
        resolution: '4000x3000',
        fileSize: '9.3 MB',
        uploadDate: '2024-11-05',
        lastModified: '2024-11-05',
        featured: false,
        downloadCount: 12,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 9,
        isPublic: true
      }
    ]
  }),
  
  getters: {
    upcomingEvents: (state) => {
      const today = new Date()
      return state.events.filter(event => new Date(event.date) >= today)
        .sort((a, b) => new Date(a.date) - new Date(b.date))
    },
    
    getActivityById: (state) => (id) => {
      return state.activities.find(activity => activity.id === id)
    },
    
    getEventById: (state) => (id) => {
      return state.events.find(event => event.id === id)
    },
    
    getGalleryByCategory: (state) => (category) => {
      if (category === 'all') return state.gallery
      return state.gallery.filter(item => item.category === category)
    }
  },
  
  actions: {
    addEvent(event) {
      this.events.push({
        id: this.events.length + 1,
        ...event
      })
    },
    
    updateEvent(id, updates) {
      const index = this.events.findIndex(event => event.id === id)
      if (index !== -1) {
        this.events[index] = { ...this.events[index], ...updates }
      }
    }
  }
}) 