import { defineStore } from 'pinia'

export const useMainStore = defineStore('main', {
  state: () => ({
    activities: [
      {
        id: 1,
        name: 'Fitness',
        description: 'Séances de renforcement musculaire et cardio adaptées à tous les niveaux. Améliorez votre force, endurance et tonus musculaire.',
        schedule: 'Lundi, Mercredi, Vendredi - 18h00-19h30',
        location: 'Salle de sport du Centre Culturel',
        image: '/images/fitness.jpg',
        color: 'cacao',
        benefits: ['Renforcement musculaire', 'Amélioration cardio', 'Perte de poids', 'Tonification'],
        instructor: 'Coach Michel',
        level: 'Tous niveaux',
        equipment: 'Matériel fourni',
        address: 'Centre Culturel, Avenue de la Paix, Brazzaville',
        capacity: 25,
        price: '15 000 FCFA/mois',
        duration: '1h30',
        difficulty: 'Intermédiaire',
        maxAge: 'Aucune limite',
        minAge: 16,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Tenue de sport confortable',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Gratuit',
        showers: 'Disponibles',
        wifi: 'Gratuit',
        lockers: 'Disponibles',
        airConditioning: 'Oui',
        music: 'Playlist motivante',
        firstClass: 'Lundi 18h00',
        lastClass: 'Vendredi 19h30',
        totalClasses: '12 par mois',
        waitingList: 'Oui',
        cancellationPolicy: '24h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -20%', 'Groupes: -15%'],
        activityStatus: 'Active',
        currentParticipants: 18
      },
      {
        id: 2,
        name: 'Danse',
        description: 'Danse moderne et traditionnelle africaine pour tous. Découvrez la joie du mouvement et la culture africaine.',
        schedule: 'Mardi, Jeudi - 17h00-18h30',
        location: 'Studio de danse',
        image: '/images/dance.jpg',
        color: 'raspberry',
        benefits: ['Coordination', 'Souplesse', 'Culture africaine', 'Expression artistique'],
        instructor: 'Coach Fatou',
        level: 'Débutant à avancé',
        equipment: 'Tenue confortable',
        address: 'Studio de danse FlexBeat, Rue du Commerce, Brazzaville',
        capacity: 20,
        price: '20 000 FCFA/mois',
        duration: '1h30',
        difficulty: 'Tous niveaux',
        maxAge: 'Aucune limite',
        minAge: 12,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Tenue souple et chaussettes',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Payant (500 FCFA)',
        showers: 'Non disponibles',
        wifi: 'Gratuit',
        lockers: 'Disponibles',
        airConditioning: 'Oui',
        music: 'Musique africaine traditionnelle',
        firstClass: 'Mardi 17h00',
        lastClass: 'Jeudi 18h30',
        totalClasses: '8 par mois',
        waitingList: 'Oui',
        cancellationPolicy: '24h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -25%', 'Groupes: -20%'],
        activityStatus: 'Active',
        currentParticipants: 15
      },
      {
        id: 3,
        name: 'Cardio Plein Air',
        description: 'Course à pied et exercices en extérieur dans la nature. Profitez du grand air pour vos séances cardio.',
        schedule: 'Samedi - 7h00-8h30',
        location: 'Parc de la Révolution',
        image: '/images/cardio.jpg',
        color: 'sunny',
        benefits: ['Endurance cardio', 'Vitesse', 'Plein air', 'Nature'],
        instructor: 'Coach Jean',
        level: 'Tous niveaux',
        equipment: 'Baskets de course',
        address: 'Parc de la Révolution, Brazzaville',
        capacity: 40,
        price: '10 000 FCFA/mois',
        duration: '1h30',
        difficulty: 'Tous niveaux',
        maxAge: 'Aucune limite',
        minAge: 14,
        gender: 'Mixte',
        language: 'Français',
        requirements: 'Baskets de course et bouteille d\'eau',
        insurance: 'Incluse dans l\'adhésion',
        parking: 'Gratuit',
        showers: 'Non disponibles',
        wifi: 'Non disponible',
        lockers: 'Non disponibles',
        airConditioning: 'Non (plein air)',
        music: 'Nature et motivation',
        firstClass: 'Samedi 7h00',
        lastClass: 'Samedi 8h30',
        totalClasses: '4 par mois',
        waitingList: 'Non',
        cancellationPolicy: '2h à l\'avance',
        trialClass: 'Oui (gratuite)',
        membershipOptions: ['Mensuel', 'Trimestriel', 'Annuel'],
        specialOffers: ['Étudiants: -30%', 'Groupes: -25%'],
        activityStatus: 'Active',
        currentParticipants: 28
      }
    ],
    events: [
      {
        id: 1,
        title: 'Marathon de Brazzaville',
        date: '2025-03-15',
        time: '7h00',
        location: 'Centre-ville de Brazzaville',
        description: 'Course de 10km ouverte à tous les niveaux. Parcours urbain avec vue sur le fleuve Congo.',
        image: '/images/marathon.jpg',
        registrationRequired: true,
        maxParticipants: 500,
        price: 'Gratuit',
        organizer: 'FlexBeat en partenariat avec la Mairie',
        category: 'Course à pied',
        duration: '3 heures',
        ageMin: 16,
        registrationDeadline: '2025-03-10',
        prizes: ['Médaille pour tous', 'Trophées pour les 3 premiers'],
        sponsors: ['Mairie de Brazzaville', 'Orange Congo', 'Total Energies'],
        route: 'Départ: Place de la République - Arrivée: Place de la Paix',
        weather: 'Saison sèche, température agréable',
        facilities: ['Points de ravitaillement', 'Médecins', 'Toilettes'],
        contact: 'marathon@flexbeat.cg',
        phone: '+242 06 123 45 67',
        website: 'www.marathon-brazzaville.cg',
        socialMedia: '@marathon_brazzaville',
        registrationLink: 'https://forms.gle/marathon2025',
        maxRegistrationDate: '2025-03-10',
        startLocation: 'Place de la République',
        finishLocation: 'Place de la Paix',
        elevation: '120m',
        distance: '10km',
        terrain: 'Urbain',
        waterStations: 5,
        medicalStations: 3,
        timingChip: 'Oui',
        eventType: 'Compétition',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 2,
        title: 'Festival du Sport',
        date: '2025-02-20',
        time: '14h00',
        location: 'Stade Alphonse Massamba-Débat',
        description: 'Démonstrations et initiations sportives pour toute la famille. Stands, animations et compétitions.',
        image: '/images/festival.jpg',
        registrationRequired: false,
        maxParticipants: 1000,
        price: 'Gratuit',
        organizer: 'FlexBeat',
        category: 'Festival',
        duration: '6 heures',
        ageMin: 'Tous âges',
        registrationDeadline: 'N/A',
        prizes: ['Animations gratuites', 'Initiation aux sports'],
        sponsors: ['Ministère des Sports', 'Fédération Congolaise'],
        route: 'Stade Alphonse Massamba-Débat - Stands et animations',
        weather: 'Saison sèche, ensoleillé',
        facilities: ['Stands de restauration', 'Animations pour enfants', 'Parking gratuit'],
        contact: 'festival@flexbeat.cg',
        phone: '+242 06 123 45 68',
        website: 'www.festival-sport-congo.cg',
        socialMedia: '@festival_sport_congo',
        registrationLink: 'N/A',
        maxRegistrationDate: 'N/A',
        startLocation: 'Stade Alphonse Massamba-Débat',
        finishLocation: 'Stade Alphonse Massamba-Débat',
        elevation: '320m',
        distance: 'N/A',
        terrain: 'Stade',
        waterStations: 'N/A',
        medicalStations: 2,
        timingChip: 'Non',
        eventType: 'Festival',
        registrationStatus: 'Non requis',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 3,
        title: 'Stage de Danse Africaine',
        date: '2025-01-25',
        time: '10h00',
        location: 'Studio de danse FlexBeat',
        description: 'Stage intensif de danse africaine traditionnelle et moderne. Tous niveaux acceptés.',
        image: '/images/dance-stage.jpg',
        registrationRequired: true,
        maxParticipants: 30,
        price: '25 000 FCFA',
        organizer: 'Coach Fatou',
        category: 'Stage',
        duration: '4 heures',
        ageMin: 12,
        registrationDeadline: '2025-01-20',
        prizes: ['Certificat de participation', 'Spectacle de fin de stage'],
        sponsors: ['Studio FlexBeat', 'Association des Danseurs'],
        route: 'Studio de danse FlexBeat - Spectacle final',
        weather: 'Saison sèche, intérieur climatisé',
        facilities: ['Studio climatisé', 'Vestiaires', 'Matériel fourni'],
        contact: 'danse@flexbeat.cg',
        phone: '+242 06 123 45 69',
        website: 'www.stage-danse-africaine.cg',
        socialMedia: '@stage_danse_africaine',
        registrationLink: 'https://forms.gle/danse2025',
        maxRegistrationDate: '2025-01-20',
        startLocation: 'Studio de danse FlexBeat',
        finishLocation: 'Studio de danse FlexBeat',
        elevation: '280m',
        distance: 'N/A',
        terrain: 'Intérieur',
        waterStations: 'N/A',
        medicalStations: 1,
        timingChip: 'Non',
        eventType: 'Stage',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      },
      {
        id: 4,
        title: 'Challenge Fitness',
        date: '2025-04-10',
        time: '16h00',
        location: 'Salle de sport du Centre Culturel',
        description: 'Compétition de fitness par équipes. Épreuves de force, endurance et coordination.',
        image: '/images/fitness-challenge.jpg',
        registrationRequired: true,
        maxParticipants: 100,
        price: '15 000 FCFA',
        organizer: 'Coach Michel',
        category: 'Compétition',
        duration: '2 heures',
        ageMin: 18,
        registrationDeadline: '2025-04-05',
        prizes: ['Trophées pour les 3 premières équipes', 'Médaille pour tous les participants'],
        sponsors: ['Centre Culturel', 'Fédération de Fitness'],
        route: 'Salle de sport - Épreuves par équipes',
        weather: 'Saison des pluies, intérieur',
        facilities: ['Salle climatisée', 'Matériel de compétition', 'Vestiaires'],
        contact: 'fitness@flexbeat.cg',
        phone: '+242 06 123 45 70',
        website: 'www.challenge-fitness-congo.cg',
        socialMedia: '@challenge_fitness_congo',
        registrationLink: 'https://forms.gle/fitness2025',
        maxRegistrationDate: '2025-04-05',
        startLocation: 'Salle de sport du Centre Culturel',
        finishLocation: 'Salle de sport du Centre Culturel',
        elevation: '120m',
        distance: 'N/A',
        terrain: 'Intérieur',
        waterStations: 'N/A',
        medicalStations: 2,
        timingChip: 'Oui',
        eventType: 'Compétition',
        registrationStatus: 'Ouvert',
        eventStatus: 'À venir',
        registrationCount: 0
      }
    ],
    testimonials: [
      {
        id: 1,
        name: 'Marie K.',
        role: 'Membre depuis 2 ans',
        content: 'FlexBeat m\'a permis de retrouver la forme et de rencontrer des personnes passionnées par le sport. L\'ambiance est incroyable !',
        avatar: '/images/avatar1.jpg',
        activity: 'Fitness',
        rating: 5,
        age: 28,
        profession: 'Infirmière',
        joinDate: '2022-01-15',
        favoriteActivity: 'Renforcement musculaire',
        goals: 'Perte de poids et tonification',
        achievements: 'Perdu 8kg, amélioré ma condition physique',
        frequency: '3 fois par semaine',
        motivation: 'Santé et bien-être',
        location: 'Brazzaville Centre',
        socialMedia: '@marie_fitness',
        beforeWeight: '68kg',
        afterWeight: '60kg',
        favoriteCoach: 'Coach Michel',
        favoriteTime: '18h00',
        favoriteDay: 'Mercredi',
        beforePhoto: '/images/before-marie.jpg',
        afterPhoto: '/images/after-marie.jpg',
        totalClasses: 156,
        favoriteEquipment: 'Haltères',
        personalBest: 'Squat 50kg',
        membershipType: 'Annuel',
        referralCount: 3,
        favoriteClass: 'Renforcement musculaire',
        improvement: 'Très satisfaite',
        testimonialDate: '2024-12-01',
        verified: true
      },
      {
        id: 2,
        name: 'Jean P.',
        role: 'Membre depuis 1 an',
        content: 'Les séances sont variées et adaptées à tous les niveaux. L\'ambiance est excellente et les coachs sont très professionnels !',
        avatar: '/images/avatar2.jpg',
        activity: 'Cardio',
        rating: 5,
        age: 35,
        profession: 'Ingénieur',
        joinDate: '2023-01-10',
        favoriteActivity: 'Course à pied',
        goals: 'Améliorer mon endurance cardio',
        achievements: 'Parcours 10km en 45 minutes',
        frequency: '2 fois par semaine',
        motivation: 'Performance sportive',
        location: 'Brazzaville Nord',
        socialMedia: '@jean_runner',
        beforeTime: '55 minutes',
        afterTime: '45 minutes',
        favoriteCoach: 'Coach Jean',
        favoriteTime: '7h00',
        favoriteDay: 'Samedi',
        beforePhoto: '/images/before-jean.jpg',
        afterPhoto: '/images/after-jean.jpg',
        totalClasses: 52,
        favoriteEquipment: 'Chronomètre',
        personalBest: '10km en 45 minutes',
        membershipType: 'Annuel',
        referralCount: 1,
        favoriteClass: 'Course à pied',
        improvement: 'Très satisfait',
        testimonialDate: '2024-11-28',
        verified: true
      },
      {
        id: 3,
        name: 'Sarah M.',
        role: 'Membre depuis 6 mois',
        content: 'J\'adore les cours de danse ! C\'est une excellente façon de faire du sport tout en s\'amusant et en découvrant la culture africaine.',
        avatar: '/images/avatar3.jpg',
        activity: 'Danse',
        rating: 5,
        age: 24,
        profession: 'Étudiante',
        joinDate: '2023-07-01',
        favoriteActivity: 'Danse traditionnelle',
        goals: 'Apprendre la danse africaine et s\'amuser',
        achievements: 'Participé au spectacle de fin d\'année',
        frequency: '2 fois par semaine',
        motivation: 'Culture et divertissement',
        location: 'Brazzaville Sud',
        socialMedia: '@sarah_dance',
        beforeLevel: 'Débutant',
        afterLevel: 'Intermédiaire',
        favoriteCoach: 'Coach Fatou',
        favoriteTime: '17h00',
        favoriteDay: 'Mardi',
        beforePhoto: '/images/before-sarah.jpg',
        afterPhoto: '/images/after-sarah.jpg',
        totalClasses: 26,
        favoriteEquipment: 'Tambour',
        personalBest: 'Spectacle de fin d\'année',
        membershipType: 'Mensuel',
        referralCount: 2,
        favoriteClass: 'Danse traditionnelle',
        improvement: 'Très satisfaite',
        testimonialDate: '2024-11-25',
        verified: true
      },
      {
        id: 4,
        name: 'David L.',
        role: 'Membre depuis 3 ans',
        content: 'Le cardio plein air est parfait pour moi. C\'est motivant de faire du sport en groupe dans la nature de Brazzaville.',
        avatar: '/images/avatar4.jpg',
        activity: 'Cardio',
        rating: 5,
        age: 42,
        profession: 'Enseignant',
        joinDate: '2021-03-20',
        favoriteActivity: 'Exercices en plein air',
        goals: 'Maintenir une bonne condition physique',
        achievements: 'Membre fidèle, ambassadeur FlexBeat',
        frequency: '1 fois par semaine',
        motivation: 'Santé et nature',
        location: 'Brazzaville Est',
        socialMedia: '@david_outdoor',
        beforeCondition: 'Moyenne',
        afterCondition: 'Excellente',
        favoriteCoach: 'Coach Jean',
        favoriteTime: '7h00',
        favoriteDay: 'Samedi',
        beforePhoto: '/images/before-david.jpg',
        afterPhoto: '/images/after-david.jpg',
        totalClasses: 156,
        favoriteEquipment: 'Gilet réfléchissant',
        personalBest: 'Ambassadeur FlexBeat',
        membershipType: 'Annuel',
        referralCount: 5,
        favoriteClass: 'Exercices en plein air',
        improvement: 'Très satisfait',
        testimonialDate: '2024-11-20',
        verified: true
      }
    ],
    gallery: [
      {
        id: 1,
        title: 'Séance de Fitness',
        category: 'fitness',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Groupe de fitness en pleine séance de renforcement musculaire',
        date: '2024-12-01',
        photographer: 'Coach Michel',
        tags: ['fitness', 'groupe', 'musculation'],
        likes: 45,
        views: 120,
        location: 'Salle de sport du Centre Culturel',
        participants: 15,
        equipment: ['Haltères', 'Tapis de sol', 'Barres de traction'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '28°C',
        hashtags: ['#FlexBeat', '#Fitness', '#Brazzaville'],
        camera: 'Canon EOS R6',
        settings: 'f/2.8, 1/200s, ISO 400',
        resolution: '4000x3000',
        fileSize: '8.5 MB',
        uploadDate: '2024-12-01',
        lastModified: '2024-12-01',
        featured: true,
        downloadCount: 12,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 1,
        isPublic: true
      },
      {
        id: 2,
        title: 'Cours de Danse',
        category: 'dance',
        image: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=200&h=150&fit=crop',
        description: 'Cours de danse africaine traditionnelle',
        date: '2024-11-28',
        photographer: 'Coach Fatou',
        tags: ['danse', 'africaine', 'traditionnelle'],
        likes: 38,
        views: 95,
        location: 'Studio de danse FlexBeat',
        participants: 12,
        equipment: ['Tambours', 'Costumes traditionnels', 'Système audio'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '30°C',
        hashtags: ['#FlexBeat', '#DanseAfricaine', '#Culture'],
        camera: 'Sony A7 III',
        settings: 'f/4.0, 1/160s, ISO 800',
        resolution: '4000x3000',
        fileSize: '7.2 MB',
        uploadDate: '2024-11-28',
        lastModified: '2024-11-28',
        featured: false,
        downloadCount: 8,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 2,
        isPublic: true
      },
      {
        id: 3,
        title: 'Cardio en Plein Air',
        category: 'cardio',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Séance de cardio dans le parc de la Révolution',
        date: '2024-11-25',
        photographer: 'Coach Jean',
        tags: ['cardio', 'plein air', 'parc'],
        likes: 52,
        views: 135,
        location: 'Parc de la Révolution',
        participants: 25,
        equipment: ['Cones de course', 'Chronomètres', 'Gilets réfléchissants'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '26°C',
        hashtags: ['#FlexBeat', '#Cardio', '#PleinAir'],
        camera: 'Nikon Z6',
        settings: 'f/5.6, 1/125s, ISO 200',
        resolution: '4000x3000',
        fileSize: '9.1 MB',
        uploadDate: '2024-11-25',
        lastModified: '2024-11-25',
        featured: true,
        downloadCount: 15,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 3,
        isPublic: true
      },
      {
        id: 4,
        title: 'Événement Sportif',
        category: 'events',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Festival du sport 2024',
        date: '2024-11-20',
        photographer: 'Équipe FlexBeat',
        tags: ['événement', 'festival', 'sport'],
        likes: 67,
        views: 180,
        location: 'Stade Alphonse Massamba-Débat',
        participants: 300,
        equipment: ['Stands d\'exposition', 'Matériel sportif', 'Système de son'],
        duration: '6 heures',
        season: 'Saison sèche',
        temperature: '32°C',
        hashtags: ['#FlexBeat', '#FestivalSport', '#Congo'],
        camera: 'Canon EOS R5',
        settings: 'f/3.2, 1/100s, ISO 640',
        resolution: '4000x3000',
        fileSize: '10.3 MB',
        uploadDate: '2024-11-20',
        lastModified: '2024-11-20',
        featured: true,
        downloadCount: 22,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 4,
        isPublic: true
      },
      {
        id: 5,
        title: 'Groupe de Fitness',
        category: 'fitness',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Équipe de fitness FlexBeat',
        date: '2024-11-18',
        photographer: 'Coach Michel',
        tags: ['fitness', 'équipe', 'groupe'],
        likes: 41,
        views: 110,
        location: 'Salle de sport du Centre Culturel',
        participants: 18,
        equipment: ['Machines de musculation', 'Haltères', 'Tapis de yoga'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '29°C',
        hashtags: ['#FlexBeat', '#TeamFitness', '#Motivation'],
        camera: 'Canon EOS R6',
        settings: 'f/2.8, 1/200s, ISO 400',
        resolution: '4000x3000',
        fileSize: '8.7 MB',
        uploadDate: '2024-11-18',
        lastModified: '2024-11-18',
        featured: false,
        downloadCount: 9,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 5,
        isPublic: true
      },
      {
        id: 6,
        title: 'Danse Traditionnelle',
        category: 'dance',
        image: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=200&h=150&fit=crop',
        description: 'Spectacle de danse traditionnelle',
        date: '2024-11-15',
        photographer: 'Coach Fatou',
        tags: ['danse', 'spectacle', 'traditionnelle'],
        likes: 58,
        views: 145,
        location: 'Studio de danse FlexBeat',
        participants: 20,
        equipment: ['Costumes colorés', 'Tambours traditionnels', 'Éclairage scénique'],
        duration: '2 heures',
        season: 'Saison sèche',
        temperature: '31°C',
        hashtags: ['#FlexBeat', '#DanseTraditionnelle', '#Spectacle'],
        camera: 'Sony A7 III',
        settings: 'f/4.0, 1/160s, ISO 800',
        resolution: '4000x3000',
        fileSize: '7.8 MB',
        uploadDate: '2024-11-15',
        lastModified: '2024-11-15',
        featured: true,
        downloadCount: 18,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 6,
        isPublic: true
      },
      {
        id: 7,
        title: 'Course Matinale',
        category: 'cardio',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Groupe de course matinale',
        date: '2024-11-12',
        photographer: 'Coach Jean',
        tags: ['course', 'matinale', 'groupe'],
        likes: 44,
        views: 115,
        location: 'Parc de la Révolution',
        participants: 22,
        equipment: ['Chronomètres', 'Gilets réfléchissants', 'Bouteilles d\'eau'],
        duration: '1h30',
        season: 'Saison sèche',
        temperature: '25°C',
        hashtags: ['#FlexBeat', '#CourseMatinale', '#PleinAir'],
        camera: 'Nikon Z6',
        settings: 'f/5.6, 1/125s, ISO 200',
        resolution: '4000x3000',
        fileSize: '8.9 MB',
        uploadDate: '2024-11-12',
        lastModified: '2024-11-12',
        featured: false,
        downloadCount: 11,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 7,
        isPublic: true
      },
      {
        id: 8,
        title: 'Marathon 2024',
        category: 'events',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=150&fit=crop',
        description: 'Marathon de Brazzaville 2024',
        date: '2024-11-10',
        photographer: 'Équipe FlexBeat',
        tags: ['marathon', 'course', 'événement'],
        likes: 73,
        views: 200,
        location: 'Centre-ville de Brazzaville',
        participants: 450,
        equipment: ['Dossards', 'Points de ravitaillement', 'Médecins'],
        duration: '3 heures',
        season: 'Saison sèche',
        temperature: '27°C',
        hashtags: ['#FlexBeat', '#MarathonBrazzaville', '#Course'],
        camera: 'Canon EOS R5',
        settings: 'f/3.2, 1/100s, ISO 640',
        resolution: '4000x3000',
        fileSize: '11.2 MB',
        uploadDate: '2024-11-10',
        lastModified: '2024-11-10',
        featured: true,
        downloadCount: 25,
        imageType: 'Photo',
        quality: 'HD',
        galleryPosition: 8,
        isPublic: true
      }
    ]
  }),
  
  getters: {
    upcomingEvents: (state) => {
      const today = new Date()
      return state.events.filter(event => new Date(event.date) >= today)
        .sort((a, b) => new Date(a.date) - new Date(b.date))
    },
    
    getActivityById: (state) => (id) => {
      return state.activities.find(activity => activity.id === id)
    },
    
    getEventById: (state) => (id) => {
      return state.events.find(event => event.id === id)
    },
    
    getGalleryByCategory: (state) => (category) => {
      if (category === 'all') return state.gallery
      return state.gallery.filter(item => item.category === category)
    }
  },
  
  actions: {
    addEvent(event) {
      this.events.push({
        id: this.events.length + 1,
        ...event
      })
    },
    
    updateEvent(id, updates) {
      const index = this.events.findIndex(event => event.id === id)
      if (index !== -1) {
        this.events[index] = { ...this.events[index], ...updates }
      }
    }
  }
}) 